# Site settings
title: Freezer Burn
email: kak.bo.che@gmail.com
description: The QueLab project to reduce freezer burn using sensors on the chillhub smart refrigerator.
baseurl: "/freezer_burn/" # the subpath of your site, e.g. /blog/
url: "http://quelab.github.io/freezer_burn" # the base hostname & protocol for your site
github_username:  kak-bo-che

# Build settings
markdown: redcarpet
markdown_ext:  markdown,mkdown,mkdn,mkd,md

exclude: [vendor]

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "with_toc_data", "fenced_code_blocks"]